server:
  port: 8000
fdfs:
  soTimeout: 1500   #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  reqHost: 192.168.221.133   #nginx访问地址
  reqPort: 8001              #nginx访问端口
#  thumb-image: #缩略图生成参数，可选
#    width: 1500
#    height: 1500
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加
    - 192.168.221.133:22122
spring:
  servlet:
    multipart:
      max-file-size:  100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/
      suffix:  .jsp

